### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by adg7660** [FreeRTOS/FreeRTOS#905] opened 2022-12-28 03:05 UTC
**Describe the bug**
Run freertos under windows.Create a task, only vTaskDelay (pdMS_TO_TICKS(1000)) is performed in the task; delay, and then call the FreeRTOS xTaskGetTickCount() function and the windows GetTickCount() function respectively to print, the final result is 1000 milliseconds apart

**Target**
- Development board: Windows device emulator
- Instruction Set Architecture: x64
- IDE and version: vs2019
- Toolchain and version: default

**Host**
- Host OS:Windows
- Version: Windows10

**To Reproduce**
- Use project:WIN32-MSVC-Static-Allocation-Only
demo code:
```c
static void test1_thread(void *arg)
{
    while(1)
    {
        vTaskDelay(pdMS_TO_TICKS(1000));

        printf("--> test1 %8d %d\r\n", xTaskGetTickCount(), GetTickCount());
    }
}
```

**Expected behavior**
When the code was actually executed in the end, the printing result was 1000 milliseconds apart

**Screenshots**
![image](https://user-images.githubusercontent.com/8485572/209750717-2a5b4daf-ba41-4650-a782-dc80d50cd682.png)

**Comment by rawalexe** [comment] 2022-12-28 18:22
Hello thank you for reaching out, with ticks there are expected to be equivalent to a (millisecond)[https://github.com/FreeRTOS/FreeRTOS/blob/6f7f9fd9ed56fbb34d5314af21f17cfa571133a7/FreeRTOS/Demo/WIN32-MSVC/FreeRTOSConfig.h#L47]. And in the current context they it appears that the task is delayed by 1000 milliseconds. Can you please elaborate on your expected behaviours.

**Comment by adg7660** [comment] 2022-12-29 00:57
My configTICK_RATE_HZ macro defines 1000. My problem is that the number of ticks obtained by xTaskGetTickCount() is inconsistent with the number of ticks obtained by the Windows system API interface GetTickCount()

> Hello thank you for reaching out, with ticks there are expected to be equivalent to a [millisecond](https://github.com/FreeRTOS/FreeRTOS/blob/6f7f9fd9ed56fbb34d5314af21f17cfa571133a7/FreeRTOS/Demo/WIN32-MSVC/FreeRTOSConfig.h#L47). And in the current context they it appears that the task is delayed by 1000 milliseconds. Can you please elaborate on your expected behaviors.

My configTICK_RATE_HZ macro defines 1000. My problem is that the number of ticks obtained by xTaskGetTickCount() is inconsistent with the number of ticks obtained by the Windows system API interface GetTickCount()

**Comment by adg7660** [comment] 2022-12-29 01:01
The interval displayed by xTaskGetTickCount() is 1000 milliseconds.However, the tick display interval obtained by the Windows system API GetTickCount() is 2000 milliseconds

**Comment by amazonKamath** [comment] 2022-12-30 07:01
Hello @adg7660,

The tick interrupt simulated on [windows port ](https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/6d65558ba01141d7c50ff6f93a4054cc5f16940e/portable/MSVC-MingW/port.c#L140) is based on sleep(), which is not guaranteed to be realtime. The windows port simulates realtime behavior by slowing down time and pretends every 'X' ms = 1 ms. The windows port is good place to develop code which can be later moved and tested on real hardware, but the port can't behave as RTOS.

**Comment by aggarg** [comment] 2023-01-02 05:17
Windows port simulates FreeRTOS tasks using Windows threads. The RTOS port layer just suspends and resumes these threads and the actual scheduling of threads is done by Windows. It is because of this inherent dependency on the Windows scheduler that this port cannot be timing accurate. As @amazonKamath explained, Windows port is meant to speed up the development and not necessarily for timing accuracy. I am closing this - feel free to re-open if you need anything else.

Thanks.

**Closed by aggarg** 2023-01-02 05:17 UTC
Labels: bug
