### ISSUE TITLE
Initialize task error value to zero when creating the TCB of a new task

### ISSUE THREAD

**Issue by djemaiMohamed** [FreeRTOS/FreeRTOS#1188] opened 2024-03-01 20:08 UTC
**Describe the bug**
When creating a new task, the task error value is not initialized to zero. The variable `pxNewTCB->iTaskErrno` will end up taking what was in the memory address where it is located.

The fix is to initialize the TCB error value during initialization. Here is a suggested fix to the bug:
the following function is located in tasks.c file:
```
static void prvInitialiseNewTask( TaskFunction_t pxTaskCode,
                                  const char * const pcName, /*lint !e971 Unqualified char types are allowed for strings and single characters only. */
                                  const uint32_t ulStackDepth,
                                  void * const pvParameters,
                                  UBaseType_t uxPriority,
                                  TaskHandle_t * const pxCreatedTask,
                                  TCB_t * pxNewTCB,
                                  const MemoryRegion_t * const xRegions )
{
    StackType_t * pxTopOfStack;
    UBaseType_t x;

    // My code starts here.
    #if ( configUSE_POSIX_ERRNO == 1 )
        {
            /* Initialize task error value to zero. */
            pxNewTCB->iTaskErrno = 0;
        }
    #endif
    // My code ends here.
    .
    .
    .
```

The bug was observed after making FreeRTOS uses dynamic allocation in the heap.

**Comment by archigup** [comment] 2024-03-01 22:55
Hey, would you be willing to open a PR to fix this bug? If, not we can make the PR; let us know what you would prefer.

**Comment by djemaiMohamed** [comment] 2024-03-01 23:39
I could not push the PR, permission denied, I have to configure git, you can open the PR, thanks :)

**Comment by aggarg** [comment] 2024-03-03 17:42
As described on [this post](https://forums.freertos.org/t/invalid-task-error-value-during-initialization/19317), it is not a bug. I am closing this issue. Let us continue the discussion on the forum to keep it in one place.

**Closed by aggarg** 2024-03-03 17:42 UTC
Labels: bug
